resources:
- repo: self

trigger:
  branches:
    include:
      - master

variables: 
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

pool:
  vmImage: windows-latest

steps:
  # - task: CacheBeta@0
  #   displayName: Cache NuGet packages
  #   inputs:
  #     key: nuget | ./src/Plugin.Fingerprint/packages.lock.json
  #     path: $(NUGET_PACKAGES)

  - task: MSBuild@1
    displayName: Build & Package
    inputs:
      solution: ./src/Build.sln
      msbuildArguments: /restore /t:build /p:CreatePackage=true /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)\artifacts
      configuration: Release
      maximumCpuCount: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)\artifacts
      ArtifactName: artifacts
      publishLocation: Container
    condition: always()
